"""Per-strategy daily email summary — cohort counts, matured results, expectancy."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Any

import pandas as pd

from alphavedha.monitoring.track_record import (
    TrackStats,
    compute_track_records_by_strategy,
)


@dataclass
class StrategySummaryReport:
    report_date: date
    strategy_sections: list[dict[str, Any]]
    avoid_list_symbols: list[str]
    total_open: int
    total_matured: int

    def format_text(self) -> str:
        lines: list[str] = []
        lines.append(f"AlphaVedha Daily Strategy Report — {self.report_date}")
        lines.append("=" * 55)
        lines.append("")

        if not self.strategy_sections:
            lines.append("No paper trades found.")
        else:
            lines.append(f"Total open: {self.total_open}  |  Total matured: {self.total_matured}")
            lines.append("")

        for sec in self.strategy_sections:
            lines.append(f"--- {sec['strategy']} ---")
            lines.append(f"  Cohort size:   {sec['n_selected']}")
            lines.append(f"  Evaluated:     {sec['n_evaluated']}")
            if sec["n_evaluated"] > 0:
                lines.append(f"  Win rate (net): {sec['win_rate_net']}")
                lines.append(f"  Avg return:     {sec['avg_return_net']}")
                lines.append(f"  Total return:   {sec['total_return_net']}")
                if sec.get("sharpe_net") is not None:
                    lines.append(f"  Sharpe (net):   {sec['sharpe_net']}")
            else:
                lines.append("  (no matured trades yet)")
            lines.append("")

        if self.avoid_list_symbols:
            lines.append("Avoid list (blowup score >= 70):")
            for sym in self.avoid_list_symbols:
                lines.append(f"  - {sym}")
        else:
            lines.append("Avoid list: (empty)")

        lines.append("")
        lines.append("---")
        lines.append("Generated by AlphaVedha scheduler")
        return "\n".join(lines)


def _stats_section(strategy: str, stats: TrackStats) -> dict[str, Any]:
    return {
        "strategy": strategy,
        "n_selected": stats.n_selected,
        "n_evaluated": stats.n_evaluated,
        "win_rate_net": f"{stats.win_rate_net:.1%}" if stats.win_rate_net is not None else "N/A",
        "avg_return_net": f"{stats.avg_return_net:.2%}"
        if stats.avg_return_net is not None
        else "N/A",
        "total_return_net": f"{stats.total_return_net:.2%}",
        "sharpe_net": f"{stats.sharpe_net:.2f}" if stats.sharpe_net is not None else None,
    }


def build_strategy_summary(
    trades: pd.DataFrame,
    report_date: date,
    round_trip_cost_pct: float = 0.0047,
    avoid_list_symbols: list[str] | None = None,
) -> StrategySummaryReport:
    """Build a per-strategy summary report from paper trades."""
    if avoid_list_symbols is None:
        avoid_list_symbols = []

    if trades.empty:
        return StrategySummaryReport(
            report_date=report_date,
            strategy_sections=[],
            avoid_list_symbols=avoid_list_symbols,
            total_open=0,
            total_matured=0,
        )

    records = compute_track_records_by_strategy(trades, round_trip_cost_pct)

    sections: list[dict[str, Any]] = []
    for strategy, record in sorted(records.items()):
        sections.append(_stats_section(strategy, record.all_predictions))

    total_open = int(trades["exit_price"].isna().sum()) if "exit_price" in trades.columns else 0
    total_matured = int(trades["exit_price"].notna().sum()) if "exit_price" in trades.columns else 0

    return StrategySummaryReport(
        report_date=report_date,
        strategy_sections=sections,
        avoid_list_symbols=avoid_list_symbols,
        total_open=total_open,
        total_matured=total_matured,
    )
