"""initial schema — 13 tables

Revision ID: 05c23a1b9653
Revises: 
Create Date: 2026-05-20 22:16:31.733282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c23a1b9653'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternative_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('yoy_change', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_type', 'period_date', name='uq_alternative_data')
    )
    op.create_index('ix_alternative_data_type_date', 'alternative_data', ['data_type', 'period_date'], unique=False)
    op.create_table('daily_pnl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=False),
    sa.Column('cumulative_return', sa.Float(), nullable=False),
    sa.Column('n_positions', sa.Integer(), nullable=False),
    sa.Column('n_correct', sa.Integer(), nullable=False),
    sa.Column('n_total_predictions', sa.Integer(), nullable=False),
    sa.Column('benchmark_return', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index('ix_daily_pnl_date', 'daily_pnl', ['date'], unique=False)
    op.create_table('earnings_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('revenue_actual', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_surprise_pct', sa.Float(), nullable=True),
    sa.Column('profit_actual', sa.Float(), nullable=True),
    sa.Column('profit_estimate', sa.Float(), nullable=True),
    sa.Column('profit_surprise_pct', sa.Float(), nullable=True),
    sa.Column('expenses', sa.Float(), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'quarter', 'year', name='uq_earnings_result')
    )
    op.create_index('ix_earnings_results_announced', 'earnings_results', ['announced_date'], unique=False)
    op.create_index('ix_earnings_results_symbol', 'earnings_results', ['symbol'], unique=False)
    op.create_table('insider_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('person_name', sa.String(length=200), nullable=False),
    sa.Column('person_category', sa.String(length=100), nullable=True),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('value_lakhs', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insider_trades_date', 'insider_trades', ['trade_date'], unique=False)
    op.create_index('ix_insider_trades_symbol', 'insider_trades', ['symbol'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_news_article_hash')
    )
    op.create_index('ix_news_articles_date', 'news_articles', ['published_date'], unique=False)
    op.create_index('ix_news_articles_symbol_date', 'news_articles', ['symbol', 'published_date'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('predicted_direction', sa.Integer(), nullable=False),
    sa.Column('predicted_magnitude', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'prediction_date', name='uq_paper_trade')
    )
    op.create_index('ix_paper_trades_date', 'paper_trades', ['prediction_date'], unique=False)
    op.create_index('ix_paper_trades_symbol', 'paper_trades', ['symbol'], unique=False)
    op.create_table('promoter_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quarter_end', sa.Date(), nullable=False),
    sa.Column('promoter_pct', sa.Float(), nullable=False),
    sa.Column('pledge_pct', sa.Float(), nullable=False),
    sa.Column('public_pct', sa.Float(), nullable=False),
    sa.Column('fii_pct', sa.Float(), nullable=False),
    sa.Column('dii_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'quarter_end', name='uq_promoter_holding')
    )
    op.create_index('ix_promoter_holdings_quarter', 'promoter_holdings', ['quarter_end'], unique=False)
    op.create_index('ix_promoter_holdings_symbol', 'promoter_holdings', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promoter_holdings_symbol', table_name='promoter_holdings')
    op.drop_index('ix_promoter_holdings_quarter', table_name='promoter_holdings')
    op.drop_table('promoter_holdings')
    op.drop_index('ix_paper_trades_symbol', table_name='paper_trades')
    op.drop_index('ix_paper_trades_date', table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index('ix_news_articles_symbol_date', table_name='news_articles')
    op.drop_index('ix_news_articles_date', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index('ix_insider_trades_symbol', table_name='insider_trades')
    op.drop_index('ix_insider_trades_date', table_name='insider_trades')
    op.drop_table('insider_trades')
    op.drop_index('ix_earnings_results_symbol', table_name='earnings_results')
    op.drop_index('ix_earnings_results_announced', table_name='earnings_results')
    op.drop_table('earnings_results')
    op.drop_index('ix_daily_pnl_date', table_name='daily_pnl')
    op.drop_table('daily_pnl')
    op.drop_index('ix_alternative_data_type_date', table_name='alternative_data')
    op.drop_table('alternative_data')
    # ### end Alembic commands ###
