"""d7_new_tables

Revision ID: 6f2d6044726f
Revises: a1b2c3d4e5f6
Create Date: 2026-05-30 20:16:09.175174

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f2d6044726f"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corporate_announcements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("announced_date", sa.Date(), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "announced_date", "event_type", name="uq_corp_announcement"),
    )
    op.create_index("ix_corp_ann_date", "corporate_announcements", ["announced_date"], unique=False)
    op.create_index("ix_corp_ann_symbol", "corporate_announcements", ["symbol"], unique=False)
    op.create_table(
        "data_lineage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("table_name", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_data_lineage_symbol_date", "data_lineage", ["symbol", "date"], unique=False)
    op.create_table(
        "data_quality_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("check_type", sa.String(length=30), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("detail", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_dqr_date", "data_quality_reports", ["report_date"], unique=False)
    op.create_index("ix_dqr_symbol", "data_quality_reports", ["symbol"], unique=False)
    op.create_table(
        "intraday_ohlcv",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("last_price", sa.Float(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("tick_count", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "date"),
    )
    op.drop_index(op.f("derivatives_data_date_idx"), table_name="derivatives_data")
    op.drop_index(op.f("features_date_idx"), table_name="features")
    op.drop_index(op.f("ix_insider_trades_date"), table_name="insider_trades")
    op.drop_index(op.f("institutional_flows_date_idx"), table_name="institutional_flows")
    op.drop_index(op.f("ix_institutional_flows_date"), table_name="institutional_flows")
    op.create_index("ix_institutional_flows_date", "institutional_flows", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_institutional_flows_date", table_name="institutional_flows")
    op.create_index(
        op.f("ix_institutional_flows_date"),
        "institutional_flows",
        [sa.literal_column("date DESC")],
        unique=False,
    )
    op.create_index(
        op.f("institutional_flows_date_idx"),
        "institutional_flows",
        [sa.literal_column("date DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_insider_trades_date"), "insider_trades", ["trade_date"], unique=False)
    op.create_index(
        op.f("features_date_idx"), "features", [sa.literal_column("date DESC")], unique=False
    )
    op.create_index(
        op.f("derivatives_data_date_idx"),
        "derivatives_data",
        [sa.literal_column("date DESC")],
        unique=False,
    )
    op.drop_table("intraday_ohlcv")
    op.drop_index("ix_dqr_symbol", table_name="data_quality_reports")
    op.drop_index("ix_dqr_date", table_name="data_quality_reports")
    op.drop_table("data_quality_reports")
    op.drop_index("ix_data_lineage_symbol_date", table_name="data_lineage")
    op.drop_table("data_lineage")
    op.drop_index("ix_corp_ann_symbol", table_name="corporate_announcements")
    op.drop_index("ix_corp_ann_date", table_name="corporate_announcements")
    op.drop_table("corporate_announcements")
    # ### end Alembic commands ###
